In [ ]:
# 필요한 라이브러리를 먼저 불러옵니다.
import pandas as pd
import requests

In [23]:
def storelist(pageNo):
    url = f"https://www.hollys.co.kr/store/korea/korStore2.do?pageNo={pageNo}&sido=&gugun=&store="
    
    # requests를 이용하여 정보를 불러옵니다
    response = requests.get(url)
    df_table = pd.read_html(response.text)[0]
    return df_table

In [ ]:
# 반복문을 위한 변수를 먼저 지정해줍니다.
pageNo = 1
hollys = pd.DataFrame()

# 페이지를 반복적으로 불러 올 수 있게 반복문을 이용합니다.
while True:

    # 정보가 끝난 페이지에서는 지역 칼럼에 '등록된 지점이 없습니다' 라고 나와 break해줍니다.
    if storelist(pageNo).iloc[0]['지역'] == '등록된 지점이 없습니다.':
        break

    # page마다 나오는 results 값들을 temp에 저장시키고 df에 합쳐줍니다.
    temp =  storelist(pageNo)
    hollys = hollys.concat([hollys, temp])

    # 페이지 수를 하나씩 높혀주어 계속해서 불러올 수 있게합니다.
    pageNo = pageNo + 1

In [ ]:
# 데이터 프레임의 인덱스를 정리해줍니다.
hollys = hollys.reset_index(drop=True)
hollys

,지역,매장명,현황,주소,매장 서비스,전화번호
0,광주 북구,광주북구청점,영업중,광주광역시 북구 서방로 2 (중흥동) .,NaN,062-511-8002
1,강원 홍천군,(상)홍천휴게소R점,영업중,강원도 홍천군 화촌면 서울양양고속도로 83 .,NaN,.
2,부산 부산진구,부산시민공원점,영업중,"부산 부산진구 시민공원로 73, 푸드코트피크닉 범전동 200",NaN,.
3,충남 홍성군,충남도청점,영업중,충청남도 홍성군 홍북읍 신경리 553 .,NaN,041-631-4725
4,서울 강남구,강남역2점,영업중,"서울특별시 강남구 강남대로 422 (역삼동) 역삼동816,816-7,816-8",NaN,02-568-9056
...,...,...,...,...,...,...
522,서울 관악구,신림점,영업중,서울특별시 관악구 신림로 353-1,NaN,02-877-0019
523,서울 중구,태평로점,영업중,"서울특별시 중구 세종대로 64, 해남빌딩 1층 (태평로2가 70-5) 할리스",NaN,02-755-7795
524,서울 용산구,이태원점,영업중,서울특별시 용산구 이태원로 179,NaN,02-749-8752
525,부산 부산진구,부산서면본점,영업중,"부산광역시 부산진구 동천로 73, DS타워 1~2층 (부전동 부전동 169-1) 할리스",NaN,051-819-9117
526,서울 서대문구,신촌점,영업중,서울특별시 서대문구 연세로 34 (창천동 31-12) 할리스,NaN,02-393-2004